<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>RimManager.Storage</RootNamespace>
    <AssemblyName>RimManager.Storage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimManager.Core\RimManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Mono.Cecil" />
  </ItemGroup>

</Project>
