<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>RimManager.Integrations</RootNamespace>
    <AssemblyName>RimManager.Integrations</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RimManager.Core\RimManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
